### ISSUE TITLE
浏览器能正常拉起,但是报错无法运行后续逻辑

### ISSUE THREAD

**Issue by ddddict** [ehnait/contactPutianHospital#30]
`Traceback (most recent call last):
  File "C:\Users\90322\PycharmProjects\contactPutianHospital\main.py", line 128, in <module>
    iterate_api('api.txt')
  File "C:\Users\90322\PycharmProjects\contactPutianHospital\main.py", line 107, in iterate_api
    page = ChromiumPage(addr_driver_opts=co)
  File "C:\Users\90322\PycharmProjects\contactPutianHospital\venv\lib\site-packages\DrissionPage\chromium_page.py", line 35, in __init__
    super().__init__(addr_driver_opts, tab_id, timeout)
  File "C:\Users\90322\PycharmProjects\contactPutianHospital\venv\lib\site-packages\DrissionPage\chromium_base.py", line 50, in __init__
    self._connect_browser(tab_id)
  File "C:\Users\90322\PycharmProjects\contactPutianHospital\venv\lib\site-packages\DrissionPage\chromium_page.py", line 80, in _connect_browser
    connect_browser(self._driver_options)
  File "C:\Users\90322\PycharmProjects\contactPutianHospital\venv\lib\site-packages\DrissionPage\commons\browser.py", line 54, in connect_browser
    test_connect(ip, port)
  File "C:\Users\90322\PycharmProjects\contactPutianHospital\venv\lib\site-packages\DrissionPage\commons\browser.py", line 171, in test_connect
    raise BrowserConnectError(f'\n连接浏览器失败，可能原因：\n1、浏览器未启动\n2、{port}端口不是Chromium内核浏览器\n'
DrissionPage.errors.BrowserConnectError: 
连接浏览器失败，可能原因：
1、浏览器未启动
2、9600端口不是Chromium内核浏览器
3、该浏览器未允许控制
4、和已打开的浏览器冲突
请尝试用ChromiumOptions指定别的端口和指定浏览器路径`

有一段时间没跑了, 最近重新运行突然报这个错, 是我浏览器的问题还是代码的问题呢,辛苦作者大大看下

**Comment by ehnait** [comment]
把浏览器彻底退出在打开

如果还不行就把`.auto_port(True)  # 自动获取端口` 注释掉 ，替换成成 `.set_local_port(9111)`试试 。

https://drissionpage.cn/

**Comment by ddddict** [comment]
已解决, 升级了drissionpage至最新版本,关闭了本机的手动代理,应该是设置了手动代理导致的
